workflows:
  build_apk:
    name: Build APK
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build Debug APK
        script: |
          flutter build apk --debug
      # Eğer release APK oluşturmak istersen bu adımı aktif et
      # - name: Build Release APK
      #   script: |
      #     flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      # Release APK için
      # - build/app/outputs/flutter-apk/app-release.apk
