workflows:
  build_apk:
    name: Build APK
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
      vars:
        ANDROID_KEYSTORE: Encrypted:YOUR_KEYSTORE
        ANDROID_KEYSTORE_PASSWORD: Encrypted:YOUR_KEYSTORE_PASSWORD
        ANDROID_KEY_ALIAS: Encrypted:YOUR_KEY_ALIAS
        ANDROID_KEY_PASSWORD: Encrypted:YOUR_KEY_PASSWORD
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
